### ISSUE TITLE
Enabling background theories and python external functions in the same program

### ISSUE THREAD

**Issue by rolfmorel** [potassco/clingo-lpx#11]
I would like to use background theories and python external computation at the same time in the same program.

My use case does not combine the two. That is, I have programs with rules for theory atoms which don't use external computation and rules which use external computation which do not use theory atoms.

For a toy example, I was expecting the following to work
```prolog
#script (python)
from clingo.symbol import Number
def exp(n, m):
    return Number(n.number ** m.number)
#end.

two(2).
three(3).
eight(@exp(A,B)) :- two(A),three(B).
&sum{ C*four } = 24 :- C = A * B,two(A),three(B).
```
For all the background theories I am interested in using, Clingo[DL], Clingo[LP] and ClingoLPX, I get a stack trace and the following: `error: python support not available`. As python support is just fine for my normal Clingo install (e.g. I can run the above without the last rule just fine with `clingo`), I was expecting this to just work.

For an example which combines external computation and theory atoms, just add the following rule to the above program:
```prolog
&sum{ C*one } = 8 :- C = @exp(A,B),two(A),three(B).
```
How much effort would it be to fix this, at least for the first use case?

**Comment by rolfmorel** [comment]
The following is a workaround that should work for my first use case:

- Separate program `P`'s rules into two separate programs: `Pex` and `Pth`, the first only making use of external computation and the second only making use of background theories.
- Call `clingo --text` on `Pex` to obtain a program `Pex-text` which already has the python computation performed/the textual substitution applied to. 
- Union `Pex-text` and `Pth` to obtain the intended program `P`, that background theory-enriched `clingo`s can deal with.

**Comment by rkaminsk** [comment]
It should work, if you enable python script execution: <https://potassco.org/clingo/python-api/5.5/clingo/script.html#clingo.script.enable_python>.

**Comment by rolfmorel** [comment]
Adding `from clingo import script; script.enable_python()` to the appropriate `app.py`/`__main__.py` file of the background theory projects do indeed make the above examples work. 

Thanks Roland.
