### ISSUE TITLE
Loadable propagator for Clingo via Python API

### ISSUE THREAD

**Issue by rolfmorel** [potassco/clingo-lpx#6]
I was hoping to try out this project as a background theory *in combination* with a number of other features that Clingo offers. In particular we (developers of [Popper](https://github.com/logic-and-learning-lab/Popper)) make considerable use of the programmatic interface of Clingo, e.g. for multi-shot solving.

I have the project compiling, but I don't see how I could just load the propagator. I see in `main.cc` how this would work for a C++ project making use of this solver/propagator, but I am not seeing bindings to Python.

Are the Python bindings planned and are they much work to write up?

**Comment by rkaminsk** [comment]
It would not be that difficult to add Python bindings. It would basically mean to copy existing code from clingo-dl or clingcon and adjust it to clingo-lpx. It's just an interface after all. The only bit that requires some thought is to make sure that multi-shot solving works.

I am currently busy with other projects but can mark this issue as a todo and address it later when I have some time. No promises, though.

**Comment by rolfmorel** [comment]
Thanks Roland. Am looking forward to being able to use it (in our project which makes extensive use of multi-shot solving).

**Comment by rkaminsk** [comment]
I implemented something. Note that this is a side project and does not get the same attention as for example clingo-dl. You find development packages in the usual places (but there is no stable release yet).
